"""Proactive PDF health check - promotes the tradingref.com pre-Screening scan
(previously ad-hoc every run, see CLAUDE.md) into a permanent, reusable tool.

Permanent tool (like scripts/orphan_review.py), not a one-off. Runs two
INDEPENDENT heuristics - neither replaces the other, each catches cases the
other misses:

  1. Page-0 near-zero text + at least one embedded image - the original
     tradingref.com signature (first seen 2026-08-29, ~14 chars of text) and
     its text-less variant (seen at WSJ from 2026-09-14 onward, 0 chars).
  2. PDF metadata Producer/Creator containing "pdf-lib" - a stronger signal
     found during the 2026-09-28 investigation into the WSJ suspension and
     the NYT corruption: every confirmed-corrupt file checked (WSJ 23-25.9,
     NYT International late-Aug batch) was generated by the pdf-lib
     JavaScript library seconds-to-minutes before its Telegram post, while
     every confirmed-healthy file's Producer/Creator was empty (a real
     newspaper PDF export never sets it to this tool).

Run before Screening on newly downloaded files:

    python -m scripts.pdf_health_check                        # all files still extraction_status='pending'
    python -m scripts.pdf_health_check --file "<substring>"   # one file, by unique substring of file_name

Read-only against tracker.db and the raw PDF files - never modifies either.
"""
import argparse
import json
import sys
from pathlib import Path

import pdfplumber

from src.common.db import get_connection, init_db

sys.stdout.reconfigure(encoding="utf-8")

# Generous margin above the two signatures seen so far (0 and ~14 chars) - a
# genuine front page never comes close to this even on a light news day.
TEXT_LEN_THRESHOLD = 20
PDFLIB_MARKER = "pdf-lib"


def check_pdf(path: Path) -> dict:
    """Runs both heuristics against page 0. Always returns the raw signals
    alongside the verdict, so a caller can inspect either way, not just act
    on the boolean."""
    result = {
        "producer": None,
        "creator": None,
        "page0_text_len": None,
        "page0_images": None,
        "pdflib_signature": False,
        "text_image_signature": False,
        "suspect": False,
        "error": None,
    }
    if not path.exists():
        result["error"] = "file not found on disk"
        return result
    try:
        with pdfplumber.open(str(path)) as pdf:
            meta = pdf.metadata or {}
            producer = meta.get("Producer") or ""
            creator = meta.get("Creator") or ""
            result["producer"] = producer or None
            result["creator"] = creator or None
            result["pdflib_signature"] = PDFLIB_MARKER in producer.lower() or PDFLIB_MARKER in creator.lower()
            if len(pdf.pages) == 0:
                result["error"] = "0 pages"
            else:
                page0 = pdf.pages[0]
                text = (page0.extract_text() or "").strip()
                result["page0_text_len"] = len(text)
                result["page0_images"] = len(page0.images)
                result["text_image_signature"] = len(text) <= TEXT_LEN_THRESHOLD and len(page0.images) >= 1
    except Exception as e:
        result["error"] = repr(e)
    result["suspect"] = result["pdflib_signature"] or result["text_image_signature"]
    return result


def _print_result(label: str, r: dict) -> None:
    if r["error"]:
        print(f"  [ERROR  ] {label}  ({r['error']})")
        return
    reasons = []
    if r["pdflib_signature"]:
        reasons.append(f"pdf-lib in Producer/Creator (Producer={r['producer']!r} Creator={r['creator']!r})")
    if r["text_image_signature"]:
        reasons.append(f"page0 text_len={r['page0_text_len']} <= {TEXT_LEN_THRESHOLD} + {r['page0_images']} image(s)")
    verdict = "SUSPECT" if r["suspect"] else "ok"
    reason_str = "; ".join(reasons) if reasons else "-"
    print(f"  [{verdict:7s}] {label}  ({reason_str})")


def run(file_name_contains: str | None = None, as_json: bool = False) -> dict:
    """Returns {"checked": [...], "ok": [...], "suspects": [...]} - each entry
    {"id", "file_name"} - so a caller (like scripts/daily_autorun.py) can act
    on the verdict programmatically instead of scraping the printed text.
    `as_json` only changes what's printed to stdout, not what's returned -
    the human-readable path (as_json=False, the pre-existing default) is
    unchanged so existing manual usage keeps working exactly as before."""
    conn = get_connection()
    init_db(conn)
    if file_name_contains:
        rows = conn.execute(
            "SELECT id, file_name, local_path FROM downloaded_files WHERE file_name LIKE ?",
            (f"%{file_name_contains}%",),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT id, file_name, local_path FROM downloaded_files WHERE extraction_status = 'pending'"
        ).fetchall()
    conn.close()

    summary = {"checked": [], "ok": [], "suspects": []}
    if not rows:
        if as_json:
            print(json.dumps(summary))
        else:
            print("No matching files found (nothing pending extraction, or --file matched nothing).")
        return summary

    if not as_json:
        print(f"Checking {len(rows)} file(s)...\n")
    for row in rows:
        result = check_pdf(Path(row["local_path"]))
        entry = {"id": row["id"], "file_name": row["file_name"]}
        summary["checked"].append(entry)
        (summary["suspects"] if result["suspect"] else summary["ok"]).append(entry)
        if not as_json:
            _print_result(f"id={row['id']:<4d} {row['file_name']}", result)

    if as_json:
        print(json.dumps(summary))
    else:
        print(f"\nVERDICT: {len(summary['suspects'])} suspect file(s) of {len(summary['checked'])} checked.")
        if summary["suspects"]:
            print("Do not run Screening on these until reviewed:")
            for entry in summary["suspects"]:
                print(f"  id={entry['id']}  {entry['file_name']}")
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--file",
        dest="file_name_contains",
        help="Limit to the one file whose file_name contains this substring (for testing on a sample).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print a single JSON summary line instead of the human-readable report (for scripted callers).",
    )
    args = parser.parse_args()
    run(file_name_contains=args.file_name_contains, as_json=args.json)
